### ISSUE TITLE
Wrong namespace for the Composer project

### ISSUE THREAD

**Issue by andreasciamanna** [OnTheGoSystems/wpml-page-builders-cornerstone#1]
https://github.com/OnTheGoSystems/wpml-page-builders-cornerstone/blob/e8c22fc4e07a3764f56fe6c3570637d749b252ea/composer.json#L2

The name of the library must be `otgs/wpml-page-builders-cornerstone` exactly as any other plibrary we have.

Please let me know when it's done, so I can add it to Packagist.

**Comment by adrianosferreira** [comment]
@andreasciamanna I know, I'm still working on this. Actually, I chose to work locally first and when I have something I will push + update the library. Thanks anyway!

**Comment by andreasciamanna** [comment]
Ok but why using `adriano/wpml-page-builders-cornerstone` instead of `otgs/wpml-page-builders-cornerstone`?

The only reason I can think is to forget fixing when it's time for it.

**Comment by adrianosferreira** [comment]
@andreasciamanna I'm only testing it, pushed any composer.json without checking anything. Again, it is for testing purpose. I'd create it on my on github account but I chose to create directly in the company's one and modify later.
